name: macOS
on: [push, pull_request]

jobs:
  build-macos:
    name: AppleClang-C++${{ matrix.std }}-${{ matrix.build_type }}
    runs-on: macos-10.15
    strategy:
      fail-fast: true
      matrix:
        std: [98, 11, 14, 17, 20]
        include:
          - generator: Ninja
          - build_type: Debug

    steps:
      - uses: actions/checkout@v2

      - name: setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0

      - name: setup
        run: |
          brew install lcov

      - name: setup Environment
        if: matrix.build_type == 'Debug'
        run: |
          echo 'CXXFLAGS=--coverage' >> $GITHUB_ENV

      - name: configure
        shell: bash
        env:
          CXXFLAGS: -Wall -Wextra -Wsign-conversion -Wtautological-compare -Wformat-nonliteral -Wundef -Werror ${{env.CXXFLAGS}}
        run: |
          cmake -S . -B build_${{matrix.build_type}} \
                -DCMAKE_CXX_EXTENSIONS=OFF \
                -DCMAKE_CXX_FLAGS_DEBUG=-pedantic-errors  \
                -DCMAKE_CXX_FLAGS_RELEASE=-pedantic-errors \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_STANDARD_REQUIRED=ON \
                -G "${{matrix.generator}}" \
                -Werror
